### PR TITLE
3 align actual vs expected fields

### PR DESCRIPTION
**Pull request by SargeKolja**
I got improvement wish assigned from Mo.
Finished it. Only 4 lines. Easy to check.
Makes find unexpected difference in strings good.
Is very helping at failed test to see why.

### CODE REVIEW

**Comment by zhangzheheng12345** [comment]
Cool. I'll merge this.

(Hmmm but it seems to be a very C-like realization so perhaps I'm also thinking of a more C++-like one?)

**Comment by zhangzheheng12345** [comment]
And next time pray use **clang-format** to format the code. It's a contribution rule.

**Comment by SargeKolja** [comment]
> Cool. I'll merge this.
> 
> (Hmmm but it seems to be a very C-like realization so perhaps I'm also thinking of a more C++-like one?)

My fault. I was thinking you did not use std::string so far for private reason.
Can also do in C++ std::string, will be less lines.
Perhaps after dinner time.

**Comment by SargeKolja** [comment]
> And next time pray use **clang-format** to format the code. It's a contribution rule.

I will ask Mo about this. Not had traning with clang.

**Comment by zhangzheheng12345** [comment]
Just like to inform you that I had used `std::string` to rewrite this feature. Sorry not applying yours but I think thus is a better and more graceful solution.

**Pull request merged**
