### PR TITLE
Fix of a bug and two warnings.

### PR DESCRIPTION
**Pull request by modem-man-gmx**
While discussing with a former classmate the crazy `A=1, B=0;` -> gives `A=0` thing, you and me discussed last days, he found one more in the recent code, and by the way he fixed a compiler warning.

### CODE REVIEW

**Review by zhangzheheng12345 — CHANGES_REQUESTED** [review]
I agree that you remove `NO_COLOR()` and `NO_OUTPUT()`.And you should change the use of `NO_COLOR()` and `NO_OUTPUT()` in `test.cpp`. Updating document can be put off.

**Review by zhangzheheng12345 — CHANGES_REQUESTED** [review]
Use lower camel for variables. `fixupFailed` instead.

**Comment by modem-man-gmx** [comment]
> I agree that you remove `NO_COLOR()` and `NO_OUTPUT()`.And you should change the use of `NO_COLOR()` and `NO_OUTPUT()` in `test.cpp`. Updating document can be put off.

Hmmm ... I don't know, if I understood the 2nd sentence correctly. Did you proposed to eliminate the last two lines of:
```
CONFIG(Configurations) {
  for (; argn > 0; argn--, argc++) {
    if (std::string(*argc) == "--no-color") NO_COLOR();
    if (std::string(*argc) == "--no-output") NO_OUTPUT();
  }
  // NO_COLOR();
  // NO_OUTPUT();
}
```
I am okay with this. I would keep it as it is, because it is an easy edit to have color/output switched off. In case no command line arguments shall be used. Kind of "propsing template".

**Comment by modem-man-gmx** [comment]
> Use lower camel for variables. `finalFailed` instead.

You're right! I read your requirements not well enough. Will fix it!

**Comment by modem-man-gmx** [comment]
Hmmm ... Now I spent nearly 2 hours of learning how an existing Pull Request could get changed. Many recipes, none looking trustworthy. Do you have experience in this? Could you kindly give me a hint?

**Comment by zhangzheheng12345** [comment]
> > I agree that you remove `NO_COLOR()` and `NO_OUTPUT()`.And you should change the use of `NO_COLOR()` and `NO_OUTPUT()` in `test.cpp`. Updating document can be put off.
> 
> Hmmm ... I don't know, if I understood the 2nd sentence correctly. Did you proposed to eliminate the last two lines of:
> 
> ```
> CONFIG(Configurations) {
>   for (; argn > 0; argn--, argc++) {
>     if (std::string(*argc) == "--no-color") NO_COLOR();
>     if (std::string(*argc) == "--no-output") NO_OUTPUT();
>   }
>   // NO_COLOR();
>   // NO_OUTPUT();
> }
> ```
> 
> I am okay with this. I would keep it as it is, because it is an easy edit to have color/output switched off. In case no command line arguments shall be used. Kind of "propsing template".

I meant that you should change e.g. if(...) NO_OUTPUT(); to if(...) lightest::toOutput = false; for you 've removed NO_COLOR() and NO_OUTPUT().

**Comment by zhangzheheng12345** [comment]
> Hmmm ... Now I spent nearly 2 hours of learning how an existing Pull Request could get changed. Many recipes, none looking trustworthy. Do you have experience in this? Could you kindly give me a hint?

Just commit in your repository. Changes will immediately applied to this Pull Request.

By the way, I think you can close this Pull Request and only leave the other. I think only need to merge that one so all your changes will be applied to my repository, which has the same effect.

**Comment by modem-man-gmx** [comment]
> > > I agree that you remove `NO_COLOR()` and `NO_OUTPUT()`.And you should change the use of `NO_COLOR()` and `NO_OUTPUT()` in `test.cpp`. Updating document can be put off.
> > 
> > 
> > Hmmm ... I don't know, if I understood the 2nd sentence correctly. Did you proposed to eliminate the last two lines of:
> > ```
> > CONFIG(Configurations) {
> >   for (; argn > 0; argn--, argc++) {
> >     if (std::string(*argc) == "--no-color") NO_COLOR();
> >     if (std::string(*argc) == "--no-output") NO_OUTPUT();
> >   }
> >   // NO_COLOR();
> >   // NO_OUTPUT();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am okay with this. I would keep it as it is, because it is an easy edit to have color/output switched off. In case no command line arguments shall be used. Kind of "propsing template".
> 
> I meant that you should change e.g. if(...) NO_OUTPUT(); to if(...) lightest::toOutput = false; for you 've removed NO_COLOR() and NO_OUTPUT().

Oh, no, I did not remove the two macros. Some lines above the removal place, they are still alive. I just removed duplicates.

Yours,
Mo

**Pull request closed without merging**
