### PR TITLE
Fix for the main-result blindness.

### PR DESCRIPTION
**Pull request by modem-man-gmx**
I found a way of "inherit" the TESTs results to the global object.
Quite sure you will not keep this for ever, because there are better ways (like the function-iteration point). But it works!
Take all the commits, also the lines with
```
#if defined ...
std::cerr << ...
#endif
```
then compile with -DDEBUG=15 and follow the output. Will look like this snippet:
```
End of node "Anonymous_and_args" adds failed=okay to this->failed=okay
End of node "NoPrintf_Empty_Creations" adds failed=okay to this->failed=okay
GetFailed of 'NoPrintf_SimpleString_Creations' reports: okay
Add test result to '[[Test]]' adds failed=okay to this->failed=okay
    Add test result to 'SimpleString' adds failed=okay to this->failed=okay
    Add test result to 'SimpleString' adds failed=okay to this->failed=okay
    Add test result to 'SimpleString' adds failed=okay to this->failed=okay
    Add test result to 'SimpleString' adds failed=okay to this->failed=okay
GetFailed of 'SimpleString' reports: okay
  GetFailed of son reports: okay
  GetFailed of son reports: okay
  GetFailed of son reports: okay
  GetFailed of son reports: okay
  Add test result to 'NoPrintf_SimpleString_Creations' adds failed=okay to this->failed=okay
End of node "SimpleString" adds failed=okay to this->failed=okay
    Add test result to 'Simple_Sentence' adds failed=okay to this->failed=okay
    Add test result to 'Simple_Sentence' adds failed=okay to this->failed=okay
GetFailed of 'Simple_Sentence' reports: okay
  GetFailed of son reports: okay
  GetFailed of son reports: okay
  Add test result to 'NoPrintf_SimpleString_Creations' adds failed=okay to this->failed=okay
End of node "Simple_Sentence" adds failed=okay to this->failed=okay
    Add test result to 'Replace_Dollars' adds failed=okay to this->failed=okay
    Add test result to 'Replace_Dollars' adds failed=okay to this->failed=okay
GetFailed of 'Replace_Dollars' reports: okay
  GetFailed of son reports: okay
  GetFailed of son reports: okay
  Add test result to 'NoPrintf_SimpleString_Creations' adds failed=okay to this->failed=okay
End of node "Replace_Dollars" adds failed=okay to this->failed=okay
    Add test result to 'Creation_of_all' adds failed=okay to this->failed=okay
    Add test result to 'Creation_of_all' adds failed=fail to this->failed=okay
GetFailed of 'Creation_of_all' reports: fail
  GetFailed of son reports: okay
  GetFailed of son reports: fail
  Add test result to 'NoPrintf_SimpleString_Creations' adds failed=fail to this->failed=okay
End of node "Creation_of_all" adds failed=fail to this->failed=fail
End of node "NoPrintf_SimpleString_Creations" adds failed=okay to this->failed=fail
-----------------------------
Failed tests:
```
then observe, that `'[[Test]]'` earns the failure=okay too early, it will never get the `End of node "NoPrintf_SimpleString_Creations" adds failed=okay to this->failed=fail` reported. Seemingly because End() is only called for TEST() but never for the `Register globalRegisterTest("[[Test]]");` instance?

I hope, my tracing additions will help you better than debugging through (unreadable) STL containers.
Yours sincerely,
Mo

### CODE REVIEW

**Comment by modem-man-gmx** [comment]
BTW: could be nice for debugging to have `->name` also in the `class Data`, perhaps by using a string'ified line number or the whole expression as string.

But my major question is, which design is better:

- Shall the caller actively ask the Test about Result?
- Shall the callee actively report the result back to ist encapsulating test?
- Couldn't it be nice to have `void RunRegistered()` calling a bool function instead of a `void callerFunc`?

**Comment by zhangzheheng12345** [comment]
Emmm I can't really understand this, for there are too many outputs and I'm not familiar to your project of NoPrintf. So could you please use other small example to represent this? Or try the latest version on branch `dev`. I seem to have refactored code which may help to solve this.

**Comment by zhangzheheng12345** [comment]
Ahh I understand this!
The problem is, sub tests are run when `Testing` is destroyed, but, look into macro definition of `SUB`, you'll see that before caller function returns i.e. before `testing_` is destroyed, the test data has already been added to father data node, which means failure of sub tests will be added later and will not be included.

**Review by zhangzheheng12345 — CHANGES_REQUESTED** [review]
You should just pick out a function `Testing.End`, and then call it before test data is added to the father data node in caller functions in `TEST` and `SUB`. Remove the destructor in `Testing`.
And also please remove those debug lines and dirty hack.

**Comment by zhangzheheng12345** [comment]
> BTW: could be nice for debugging to have `->name` also in the `class Data`, perhaps by using a string'ified line number or the whole expression as string.
> 
> But my major question is, which design is better:
> 
> * Shall the caller actively ask the Test about Result?
> * Shall the callee actively report the result back to ist encapsulating test?
> * Couldn't it be nice to have `void RunRegistered()` calling a bool function instead of a `void callerFunc`?

REQ don't have names, so perhaps I don't think adding `name` in `class Data` is a must. And also expose the expression as a string is not a good abstraction.

And I've thought of let `RunRegistered` to call a function which returns bool value before but now it's not necessary either, for failure can be correctly collected now.

BTW, may I ask what does 'actively ask & report' mean? Sorry but I can't much understand.

**Comment by zhangzheheng12345** [comment]
# **Important** about this PR

I think change request I've put forward above should be accomplished, for thus indeed fixes the bug that some sub failure aren't collected in time to global data object.

And sorry but I don't really familiar with `make`, and I need to work cross-platform, so to be honest I would just like CMake (and perhaps Bazel) to be used in my project. You can use `make` right now, but I think right before this PR is merged you should remove Makefile. And to learn CMake, I suggest you see the cmake-example project. Though CMake is kind of ugly, it's sometimes convenient. (BTW Bazel is good-looking and faster, so I may use it as well.)

Additionally, please use clang-format to format source files. It seems that there are unexpected tabs and other things. And would you mind move your changes made to describe issue #8 (such as those newly added tests) to another branch, and then rollback main? So that I can merge this PR simply for its original purpose.

Sorry for putting so much requests! But to keep my project unified and tidy, these are a must. Finally, thank you for revealing and fixing the bugs, update features, adding CI and replace that fake passing badge [doge]. For the latter two I know they shall be rollback and cannot be merged in this PR, but you can put another PR later to fix issue #8 and at the same include CI feature :) (P.S. Help me also add MacOS & Windows CI! I don't really understand how to use github workflow. Thank you ver much!!!)

**Comment by modem-man-gmx** [comment]
Yes, CMake is on my list for next time. I need to read and train a lot ;-) and sometimes it is not easy to leave beloved ways. So for example make. It has recursive semantics, crazy and hard to learn from scratch. I got trained since around 1998 to use the different make variants. Earlier versions have been easier to learn because less features and less requirements in the old times.

I would highly appreciate a bit of support in two things, to be able to better support you:
- kindly give me some advice how to best create one (ore perhaps multiple?) branch(es) in my fork to provide optimal pull request to your project. Currently I changed my `main` to best fit my project needs. But I would also be okay with moving my special needs to a long time branch, then to keep my `main` in sync with yours. Though my old experience in version control systems (RCS, CVS, SVN) I am still a beginner regarding Git.
- give me some hint where to high-speed learning CMake. I would at best write CMake file which creates three .exe files, then call them in an AND-chained manner as I do with the make. Or perhaps this is impossible for CMake? In this case I could change to three single CMakeText and a script or the like.

Regarding running on MAC, I can not be any help. I hate this ultra capitalist bunch of managers at Apple Inc. So I do not own any of that devices. Moreover, I have a sign on my home: "Beware: (Apple Sign) owners are shot at!". Really.

Regarding Windows ... I never used Windows Actions in github. Are there any? It is not so complicated, I think. And you are absolutely right here by insisting on CMake. My Makefile is gnu-make and would not be available for a pure MicroSoft C++ test environment. This would prefer NMake which is a very different and less powerful dialect compared to gnu-make.

long read, let's make a strategy! My proposal:

1. you propose me what the best branching strategy is for my changes offered as PR to you.
2. I redraw all the open pull requests, then
3. I move my very special requirements to my `for_noprintf` branch, rewind my `main` to some point in your `main`, then
4. I create a number <n> of `common-develop-<n>` branches, each containing *only* one improvement per branch, then
5. I send out pull requests to you.

Please change the above list to fit our common needs at best. Then we do.

OKAY?

**Comment by modem-man-gmx** [comment]
Ahhh, I learned: if I make a PR out of one of my branches, every later commit will be added to the PR. So to have a usable, isolated PR, I need to create a single branch for every isolate-able change.

BTW:
Thanks for the clang-format hint! Cool stuff! I never noticed that feature before. Was using sometimes `astyle` for formatting and `clang` just as the better C++ compiler for projects where my `pc-lint` license was not allowed or not available.

Wouldn't it be a good idea to integrate clang-format into the CMake or the github action? 
From my gnu-make world, I would just add this to the `Makefile`:
```
stylecheck: $(ProjectSourceFiles)
    clang-format --dry-run --Werror $^ && echo "Styleguide passed." || echo "Styleguide FAILURE!"

stylerepair: $(ProjectSourceFiles)
    clang-format -i --Werror $^
    git commit -m"Style auto repair" $^
```

with the second target to be used only locally. Then I'd add to action/...yaml:

```
  - name: coding rules verification
      run: make stylecheck
```

But how this could be look like in CMakeList.txt?

**Comment by modem-man-gmx** [comment]
I retreat this PR and try it later again, after better organisation of my fork. As we talked about.
Yours,
Mo

**Pull request closed without merging**
